spring:
  application:
    name: EcommerceWebApp
  datasource:
    url: jdbc:postgresql://localhost:5432/xxxx
    username: xxxxx
    password: xxxxx
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_updates: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 10MB
  cache:
    type: redis
  data:
    redis:
      port: 6379
      host: localhost
      ssl:
        enabled: false

# Server ports and servlet-context-path
server:
  port: 8080
  servlet:
    context-path: /api/v1

# Cloudinary Setup
cloudinary:
  name: xxxxx
  api-key:  xxxxxx
  api-secret: xxxxxxx


jwt-secret-key: xxxxxx

# Set logging levels for different packages
logging:
  level:
    root: INFO
    com:
      zepox:
        EcommerceWebApp:
          controller: INFO
          service: DEBUG
          repository: TRACE

# Frontend URI
frontend:
  url:
    base: http://localhost:5173
    payment-success: http://localhost:5173/payment/success
    payment-fail: http://localhost:5173/payment/fail

# Stripe setup
stripe:
  api:
    secret-key: xx
    publishable-key: xxxxx
  webhook:
    secret: xxxxxx

# Swagger setup
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
  packages-to-scan: com.zepox.EcommerceWebApp.controller
  paths-to-match: /**